---
title: "Flowchart"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Diagramme
```{r reorder}
install.packages("pacman")
require(pacman)
p_load(DiagrammeR)
chart<-grViz("digraph flowchart {
      # node definitions with substituted label text
node [fontname = Helvetica, shape = rectangle, style=filled,color=lightgrey]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
      tab6 [label = '@@6']
node [fontname = Helvetica, shape = rectangle, style=bold]        
      m1 [label = 'n=18,171 not-vaccinated']
      m2 [label = 'n=2,587 who did not have a period in the last 12 months']
      m3 [label = 'n=537 post-menopausal or transitioning']
      m4 [label = 'n=57 who did not live in the UK']
      m5 [label = 'n=295 reporting it is too early to evaluate changes']

      # creating horizontal lines
      node [shape=none, width=0, height=0, label='']
      {rank=same; tab1 -> m1}
      {rank=same; tab2 -> m2}
      {rank=same; tab3 -> m3}
      {rank=same; tab4 -> m4}
      {rank=same; tab5 -> m5}

      # edge definitions with the node IDs
     tab1 -> tab2 -> tab3 -> tab4 -> tab5 -> tab6;

      }

      [1]: 'Questionnaire filled by n=26,710 participants who gave consent'
      [2]: 'Participants vaccinated n=8,539 '
      [3]: 'Participants who had a period in the last 12 months  n=5952'
      [4]: 'Participants who are pre-menopausal n=5415'
      [5]: 'Participants living in the UK n=5358'
      [6]: 'Final sample n=5063'

      ")
jpeg('flowchartplot.jpg')
chart
dev.off()
```


