---
title: "LASSO"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# 1. Data preparation
## Load packages

```{r packages}

# Ensures the package "pacman" is installed
if (!require("pacman")) install.packages("pacman")

# Packages available from CRAN
##############################
library(pacman)

## Load
pacman::p_load(
    glmnet, 
    mlr,
    Hmisc,
    caret,
    pROC
)
```

## Load data

```{r dataload}
# list of 5 imputed datasets
multfin <- import(here("data", "data_covid19vaccine_menstrualcycles_uk_imputed.Rda")) # imputed list
```

## manip variables

```{r lassoprep}
## getting column names for lasso (select appropriate method below and comment out others)--------------------------

mult <- multfin

# make exposure list as all columns of dataset, excluding participant ID
# exposures <- colnames(mult)[which(colnames(mult) != "participant_ID")]

# # or if you have a few columns to exclude, do it this way
# exposures <- colnames(mult)[which(colnames(mult) %nin% c("participant_ID",
#                                                          "old_outcome",
#                                                          "unwanted_var"))]

# recode as factor
for(i in seq_along(mult)){
    mult[[i]]$med_lastyr_binary_num <- 
        factor(mult[[i]]$med_lastyr_binary_num, 
               levels = c(0,1), 
               ordered = FALSE)
    
   mult[[i]]$med_lastyr_binary_num <- 
        relevel(mult[[i]]$med_lastyr_binary_num, ref = "0")
}

# recode as factor
for(i in seq_along(mult)){
    mult[[i]]$vit_lastyr_binary_num <- 
        factor(mult[[i]]$vit_lastyr_binary_num, 
               levels = c(0,1), 
               ordered = FALSE)
    
   mult[[i]]$vit_lastyr_binary_num <- 
        relevel(mult[[i]]$vit_lastyr_binary_num, ref = "0")
}

# # or else if you have a subset of vars in mind, then create list manually here
exposures <- c(
    Cs(
        age,
        ethnic_group,
        med_lastyr_binary_num, # must be factor
        vit_lastyr_binary_num, # must be factor
        maritalstatus,
        bmi_group,
        physact_before,
        income_before,
        smoke_before,
        contra_current_groupall,
        cyclelength_before_group,
        period_lengh_before_group,
        heavyperiod_before,
        cycle_irreg_before,
        nbdeliveries,
        vaccine_type,
        vaccine_timing,
        covid_group,
        covid_tested,
        vaccinated,
        changesmenses_num,
        lifesatchanges,
        disease_before_endometriosis_num,
        disease_before_pcos_num,
        disease_before_underthyroid_num,
        disease_before_overthyroid_num,
        disease_before_uterpolyp_num,
        disease_before_uterfibroid_num,
        disease_before_intercystitis_num,
        disease_before_eatingdisord_num,
        liveuk,
        vaccine_changescycle_binary
    )
)

## create function to run one-hot coding for dataset
recode_dataset <- function(x) {
    
    # rename df
    data <- x
    
    # subset df to exposures
    data <- data[exposures]
    
    ### re-code factors to numeric and create dummy vars
    
    # make duplicate dataset for recoding
    data_recoded <- data
    
    # identify factor vars
    fact <- sapply(data_recoded, is.factor)
    
    # identify ordinal factors
    ord <- sapply(data_recoded, is.ordered)
    
    # convert character strings to numbers
    data_recoded[ord] <- sapply(data_recoded[ord], as.integer)
    
    # convert to numeric
    data_recoded[ord] <- sapply(data_recoded[ord], as.numeric)
    
    ### scale
    
    # get numeric columns to scale
    nums <- sapply(data_recoded, is.numeric)
    
    # list of numeric variables to exclude from scaling
    scale_exclude <- c(
        Cs(
            vaccine_changescycle_binary, # change to correct name. Only necessary if outcome variable is not a factor
        )
    )
    
    # exclude those columns I don't want to scale
    nums[names(nums) %in% scale_exclude] <- FALSE # don't want to scale these
    
    # perform scale on all remaining numeric vars
    data_recoded[nums] <- scale(data_recoded[nums],
                                scale = TRUE)
    
    # subset to complete cases for glmnet (can't handle NAs)
    data_recoded <- data_recoded[complete.cases(data_recoded), ]
    
    # return full dataset
    return(data_recoded)
    
}

# run recoding across imputed datasets
recoded_data <- lapply(mult, recode_dataset)

# check outcome coding just in case (needs to be factor)
for(i in seq_along(recoded_data)){
    recoded_data[[i]]$vaccine_changescycle_binary <- 
        factor(recoded_data[[i]]$vaccine_changescycle_binary, 
               levels = c(0,1), 
               ordered = FALSE)
    
   recoded_data[[i]]$vaccine_changescycle_binary <- 
        relevel(recoded_data[[i]]$vaccine_changescycle_binary, ref = "0")
}

### create model matrix

# split into training/test sets
set.seed(2345) # set the seed to make partition reproducible
# create partition with same proportion of outcome variable
train.rows <- createDataPartition(y = recoded_data[[1]]$vaccine_changescycle_binary, 
                                  p = 0.70, # 70% random subsample for training
                                  list = FALSE) # do not return data as list

# subset the data
recoded_data_train <- lapply(recoded_data, function(x) x[train.rows, ])
recoded_data_test <- lapply(recoded_data, function(x) x[-train.rows, ])

# set response var (try first in just one imputed dataset before running across all imputed datasets)
y <- recoded_data_train[[1]]$vaccine_changescycle_binary 
y_rep <- recoded_data_test[[1]]$vaccine_changescycle_binary

# make model matrix of exposures (try first in just one imputed dataset before running across all imputed datasets)
x <- model.matrix(recoded_data_train[[1]]$vaccine_changescycle_binary ~ .  -1, recoded_data_train[[1]])
x_rep <- model.matrix(recoded_data_test[[1]]$vaccine_changescycle_binary ~ . - 1, recoded_data_test[[1]])

```

# LASSO Cross-validation

```{r lassocrossvalid}
# set foldid so that folds are exactly the same across all alpha CV attempts
set.seed(3456)
foldid <- sample(1:10, # 10 folds
                 size = nrow(recoded_data_train[[1]]), 
                 replace = TRUE)
## LASSO
set.seed(3456)
cv.fit.lasso <- 
    cv.glmnet(x = x,
              y = y,
              family = "binomial", 
              type.measure = "auc",
              maxit = 1000, # 1,000 iterations
              nfolds = 10, # 10-fold CV
              foldid = foldid,
              trace.it = 1, # show progress bar
              alpha = 1 # LASSO
    ) 
```

# Training set AUC 

```{r AUC}
# get max AUC from the training set
max(cv.fit.lasso$cvm)
# plot AUC values for different lambdas
plot(cv.fit.lasso)
```

# Prediction 

```{r pred}
# function to loop optimal lambda/alpha from all 5 cross-validation attempts to get coefficients
# get predicted values from lasso
pred <- predict(cv.fit.lasso, 
                newx = x_rep, 
                type = "response",
                s = cv.fit.lasso$lambda.1se, # optimized lambda value. You can also try "cv.fit.lasso$lambda.min"
                alpha = 1,
                exact = FALSE)
```

# Test set AUC

```{r AUC2}
# get AUC from test set
auc.lasso <- auc(y_rep, pred)
```

# Coefficients

```{r coeff}
# get coefficients from best lasso model
set.seed(3456)    
coefs <- coef(cv.fit.lasso, 
              newdata = x_rep, 
              s = cv.fit.lasso$lambda.1se, # optimized lambda value
              alpha = 1, 
              exact = FALSE)
# make dataframe for coefficients
coefficients <- as.data.frame(as.matrix(coefs))
# make rownames a column of exposure names
coefficients$Exposure <- rownames(coefficients)
# subset to only rows where coefficient wasn't shrunk to 0
coefficients <- coefficients[which(coefficients$Coefficient != 0), ]
```
